on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please-submodule
jobs:
  release-please-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: tag-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: conventional-changelog-data-rules
          command: github-release
      - uses: actions/checkout@v3
        if: ${{ steps.tag-release.outputs.releases_created }}
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        if: ${{ steps.tag-release.outputs.releases_created }}
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: publish
        if: ${{ steps.tag-release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          pnpm install
          pnpm publish --no-git-checks --access public
  release-pr:
    runs-on: ubuntu-latest
    needs:
      - release-please-release
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
           package-name: conventional-changelog-data-rules
           command: release-pr
